spring:
  profiles:
    active: git
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file://${user.home}/ms-config-properties/{application}/{profile},
---
spring:
  profiles: git
  cloud:
    config:
      label: noeureka
      server:
        git:
          uri: https://github.com/kmehant/netflix-oss/
          search-paths:
            - "ms-config-properties/{application}/{profile}"

