spring:
  application:
    name: eureka
server:
  port: 8761

# eureka:
#   instance:
#     prefer-ip-address: true
#     hostname: eureka
#   client:
#     enabled: true
#     register-with-eureka: false
#     fetch-registry: false

eureka:
  numberRegistrySyncRetries: 1
  instance:
    preferIpAddress: true
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  server:
    enable-self-preservation: false