feign:
  hystrix:
    enabled: true
server:
  port: 8080
spring:
  application:
    name: movie-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:movies
  password: bar
  username: penta
