server:
  port: 8082
spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:h2:mem:movies
    driver-class-name: org.h2.Driver
  username: penta
  password: bar

feign:
  hystrix:
    enabled: true

# eureka:
#   #enabled: true
#   client:
#     #registerWithEureka: true
#     fetchRegistry: true
#     serviceUrl:
#       defaultZone: http://eureka:8761/eureka
#   instance:
#     metadataMap:
#       instanceId: movie-service:8082
#     preferIpAddress: true